/*=========================================================
Object Name : DDL_ETL_RECONCILIATION_LOG
Purpose     : ETL reconciliation log DDL
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

USE WAREHOUSE SNOWFLAKE_LEARNING_WH;
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

-- SECTION 1: Object Definition
CREATE TABLE IF NOT EXISTS ETL_RECONCILIATION_LOG (
    RUN_ID                          VARCHAR(100)    NOT NULL,
    RUN_TIMESTAMP                   TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    LOAD_TYPE                       VARCHAR(20),
    WATERMARK_USED                  TIMESTAMP_NTZ,
    SOURCE_COUNT                    NUMBER(18),
    DEDUP_COUNT                     NUMBER(18),
    INSERT_COUNT                    NUMBER(18),
    UPDATE_COUNT                    NUMBER(18),
    SOFT_DELETE_COUNT               NUMBER(18),
    TARGET_COUNT_POST_LOAD          NUMBER(18),
    STATUS                          VARCHAR(20),
    ERROR_MESSAGE                   VARCHAR(4000),
    LAST_SUCCESSFUL_RUN_TIMESTAMP   TIMESTAMP_NTZ,
    SLA_MET_FLAG                    BOOLEAN,
    EXECUTION_SECONDS               NUMBER(10,2)
);

-- SECTION 2: Constraints
ALTER TABLE ETL_RECONCILIATION_LOG
    ADD CONSTRAINT IF NOT EXISTS PK_ERL_RUN_ID PRIMARY KEY (RUN_ID);

-- SECTION 3: Notes
-- One row inserted per pipeline execution.
-- LOAD_TYPE values: FULL | INCREMENTAL.
-- LAST_SUCCESSFUL_RUN_TIMESTAMP used as watermark for next incremental run.
-- SLA_MET_FLAG = TRUE when 1M records processed within 300 seconds.