/*=========================================================
Object Name : TASK_SP_LOAD_AEROSPACE_PARTS_SCD1
Purpose     : Main pipeline stored procedure
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

CREATE OR REPLACE PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_AEROSPACE_PARTS_ETL()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
-- SECTION 1: Variables

    v_run_id            VARCHAR;
    v_run_timestamp     TIMESTAMP_NTZ;
    v_load_type         VARCHAR;
    v_watermark_used    TIMESTAMP_NTZ;
    v_last_run          TIMESTAMP_NTZ;
    v_source_count      INTEGER DEFAULT 0;
    v_insert_count      INTEGER DEFAULT 0;
    v_update_count      INTEGER DEFAULT 0;
    v_dedup_count       INTEGER DEFAULT 0;
    v_soft_delete_count INTEGER DEFAULT 0;
    v_target_count_post INTEGER DEFAULT 0;
    v_execution_seconds FLOAT   DEFAULT 0;
    v_sla_met_flag      VARCHAR DEFAULT 'Y';
    v_start_time        TIMESTAMP_NTZ;
    v_end_time          TIMESTAMP_NTZ;
    v_error_message     VARCHAR DEFAULT NULL;
    v_status            VARCHAR DEFAULT 'SUCCESS';

BEGIN

    -- ----------------------------------------------------------------
    -- 1. INITIALISE RUN METADATA
    -- ----------------------------------------------------------------
    v_run_id        := GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SEQ_ETL_RUN_ID.NEXTVAL::VARCHAR;
    v_run_timestamp := CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ;
    v_start_time    := v_run_timestamp;

    -- ----------------------------------------------------------------
    -- 2. DETERMINE LOAD TYPE & WATERMARK
    -- ----------------------------------------------------------------
    -- SECTION 2: Source Processing
SELECT MAX(LAST_SUCCESSFUL_RUN_TIMESTAMP)
    INTO   v_last_run
    FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
    WHERE  STATUS = 'SUCCESS';

    -- SECTION 3: Data Validation
IF (v_last_run IS NULL) THEN
        v_load_type      := 'FULL';
        v_watermark_used := '1900-01-01 00:00:00'::TIMESTAMP_NTZ;
    ELSE
        v_load_type      := 'INCREMENTAL';
        v_watermark_used := v_last_run;
    END IF;

    -- ----------------------------------------------------------------
    -- 3. STAGE INCREMENTAL / FULL SOURCE DATA INTO TEMP TABLE
    --    Deduplication: keep the row with the latest UPDATED_AT
    --    per PART_NUMBER.
    -- ----------------------------------------------------------------
    CREATE OR REPLACE TEMPORARY TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TMP_AEROSPACE_STAGED AS
    WITH ranked AS (
        SELECT
            PART_NUMBER,
            CATEGORY,
            CERTIFICATION_STATUS,
            CREATED_AT,
            LEAD_TIME_DAYS,
            LIFECYCLE_STATUS,
            MANUFACTURER,
            REORDER_LEVEL,
            STOCK_QUANTITY,
            SUPPLIER_ID,
            UNIT_PRICE_USD,
            UPDATED_AT,
            WEIGHT_KG,
            ROW_NUMBER() OVER (
                PARTITION BY PART_NUMBER
                ORDER BY     UPDATED_AT DESC NULLS LAST
            ) AS rn
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
        WHERE (
            v_load_type = 'FULL'
            OR UPDATED_AT > v_watermark_used
        )
    ),
    deduped AS (
        SELECT * FROM ranked WHERE rn = 1
    )
    SELECT
        PART_NUMBER,
        CATEGORY,
        CERTIFICATION_STATUS,
        CREATED_AT,
        LEAD_TIME_DAYS,
        LIFECYCLE_STATUS,
        MANUFACTURER,
        REORDER_LEVEL,
        STOCK_QUANTITY,
        SUPPLIER_ID,
        UNIT_PRICE_USD,
        UPDATED_AT,
        WEIGHT_KG
    FROM deduped;

    -- ----------------------------------------------------------------
    -- 4. CAPTURE COUNTS
    -- ----------------------------------------------------------------

    -- Total source rows in scope (before dedup)
    SELECT COUNT(*)
    INTO   v_source_count
    FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
    WHERE (
        v_load_type = 'FULL'
        OR UPDATED_AT > v_watermark_used
    );

    -- Rows eliminated by deduplication
    v_dedup_count := v_source_count - (
        SELECT COUNT(*) FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TMP_AEROSPACE_STAGED
    );

    -- ----------------------------------------------------------------
    -- 5. RISK SCORE CALCULATION (inline in MERGE)
    --    Logic:
    --      +30  if CERTIFICATION_STATUS != 'CERTIFIED'
    --      +25  if LIFECYCLE_STATUS IN ('OBSOLETE','END_OF_LIFE')
    --      +20  if STOCK_QUANTITY < REORDER_LEVEL
    --      +15  if LEAD_TIME_DAYS > 90
    --      +10  if UNIT_PRICE_USD > 50000
    --    Capped at 100.
    -- ----------------------------------------------------------------

    -- ----------------------------------------------------------------
    -- 6. SCD TYPE 1 -- SECTION 4: Merge Logic
MERGE INTO TARGET
    -- ----------------------------------------------------------------
    MERGE INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET  tgt
    USING (
        SELECT
            s.PART_NUMBER,
            s.CATEGORY,
            s.CERTIFICATION_STATUS,
            s.LEAD_TIME_DAYS,
            s.LIFECYCLE_STATUS,
            s.MANUFACTURER,
            s.REORDER_LEVEL,
            s.STOCK_QUANTITY,
            s.SUPPLIER_ID,
            s.UNIT_PRICE_USD,
            s.UPDATED_AT,
            s.WEIGHT_KG,
            -- STATUS derivation
            CASE
                WHEN s.LIFECYCLE_STATUS IN ('OBSOLETE','END_OF_LIFE') THEN 'INACTIVE'
                ELSE 'ACTIVE'
            END AS DERIVED_STATUS,
            -- RISK_SCORE derivation (capped at 100)
            LEAST(
                COALESCE(
                    CASE WHEN s.CERTIFICATION_STATUS != 'CERTIFIED'              THEN 30 ELSE 0 END
                  + CASE WHEN s.LIFECYCLE_STATUS IN ('OBSOLETE','END_OF_LIFE')   THEN 25 ELSE 0 END
                  + CASE WHEN s.STOCK_QUANTITY < s.REORDER_LEVEL                 THEN 20 ELSE 0 END
                  + CASE WHEN s.LEAD_TIME_DAYS > 90                              THEN 15 ELSE 0 END
                  + CASE WHEN s.UNIT_PRICE_USD > 50000                           THEN 10 ELSE 0 END
                , 0),
                100
            ) AS DERIVED_RISK_SCORE
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TMP_AEROSPACE_STAGED s
    ) src
    ON tgt.PART_NUMBER = src.PART_NUMBER

    -- UPDATE existing records (SCD Type 1 overwrite)
    WHEN MATCHED AND (
           tgt.CATEGORY             <> src.CATEGORY
        OR tgt.CERTIFICATION_STATUS <> src.CERTIFICATION_STATUS
        OR tgt.LEAD_TIME_DAYS       <> src.LEAD_TIME_DAYS
        OR tgt.LIFECYCLE_STATUS     <> src.LIFECYCLE_STATUS
        OR tgt.MANUFACTURER         <> src.MANUFACTURER
        OR tgt.REORDER_LEVEL        <> src.REORDER_LEVEL
        OR tgt.STOCK_QUANTITY       <> src.STOCK_QUANTITY
        OR tgt.SUPPLIER_ID          <> src.SUPPLIER_ID
        OR tgt.UNIT_PRICE_USD       <> src.UNIT_PRICE_USD
        OR tgt.UPDATED_AT           <> src.UPDATED_AT
        OR tgt.WEIGHT_KG            <> src.WEIGHT_KG
    ) THEN UPDATE SET
        tgt.CATEGORY             = src.CATEGORY,
        tgt.CERTIFICATION_STATUS = src.CERTIFICATION_STATUS,
        tgt.LEAD_TIME_DAYS       = src.LEAD_TIME_DAYS,
        tgt.LIFECYCLE_STATUS     = src.LIFECYCLE_STATUS,
        tgt.MANUFACTURER         = src.MANUFACTURER,
        tgt.REORDER_LEVEL        = src.REORDER_LEVEL,
        tgt.RISK_SCORE           = src.DERIVED_RISK_SCORE,
        tgt.STATUS               = src.DERIVED_STATUS,
        tgt.STOCK_QUANTITY       = src.STOCK_QUANTITY,
        tgt.SUPPLIER_ID          = src.SUPPLIER_ID,
        tgt.UNIT_PRICE_USD       = src.UNIT_PRICE_USD,
        tgt.UPDATED_AT           = src.UPDATED_AT,
        tgt.WEIGHT_KG            = src.WEIGHT_KG,
        tgt.DW_UPDATED_AT        = CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ

    -- INSERT new records
    WHEN NOT MATCHED THEN INSERT (
        PART_NUMBER,
        CATEGORY,
        CERTIFICATION_STATUS,
        LEAD_TIME_DAYS,
        LIFECYCLE_STATUS,
        MANUFACTURER,
        REORDER_LEVEL,
        RISK_SCORE,
        STATUS,
        STOCK_QUANTITY,
        SUPPLIER_ID,
        UNIT_PRICE_USD,
        UPDATED_AT,
        WEIGHT_KG,
        DW_INSERT_TIMESTAMP,
        DW_UPDATED_AT
    ) VALUES (
        src.PART_NUMBER,
        src.CATEGORY,
        src.CERTIFICATION_STATUS,
        src.LEAD_TIME_DAYS,
        src.LIFECYCLE_STATUS,
        src.MANUFACTURER,
        src.REORDER_LEVEL,
        src.DERIVED_RISK_SCORE,
        src.DERIVED_STATUS,
        src.STOCK_QUANTITY,
        src.SUPPLIER_ID,
        src.UNIT_PRICE_USD,
        src.UPDATED_AT,
        src.WEIGHT_KG,
        CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
        CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ
    );

    -- ----------------------------------------------------------------
    -- 7. CAPTURE INSERT / UPDATE COUNTS FROM MERGE
    -- ----------------------------------------------------------------
    -- Snowflake does not expose per-clause MERGE row counts natively
    -- via SQL variables; derive from post-merge state instead.

    -- Rows inserted = rows in staged that did NOT exist in target before merge
    -- Approximate: compare staged vs matched
    SELECT COUNT(*)
    INTO   v_insert_count
    FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TMP_AEROSPACE_STAGED s
    LEFT JOIN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET t
           ON t.PART_NUMBER = s.PART_NUMBER
    WHERE  t.DW_INSERT_TIMESTAMP >= v_start_time;

    SELECT COUNT(*)
    INTO   v_update_count
    FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
    WHERE  DW_UPDATED_AT  >= v_start_time
      AND  DW_INSERT_TIMESTAMP < v_start_time;

    -- ----------------------------------------------------------------
    -- 8. SOFT-DELETE: mark records absent from source as INACTIVE
    --    (only applicable on FULL load to avoid false positives)
    -- ----------------------------------------------------------------
    IF (v_load_type = 'FULL') THEN

        UPDATE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET tgt
        SET    tgt.STATUS       = 'INACTIVE',
               tgt.DW_UPDATED_AT = CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ
        WHERE  tgt.STATUS != 'INACTIVE'
          AND  tgt.PART_NUMBER NOT IN (
                   SELECT PART_NUMBER
                   FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TMP_AEROSPACE_STAGED
               );

        v_soft_delete_count := SQLROWCOUNT;

    END IF;

    -- ----------------------------------------------------------------
    -- 9. POST-LOAD TARGET COUNT
    -- ----------------------------------------------------------------
    SELECT COUNT(*)
    INTO   v_target_count_post
    FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET;

    -- ----------------------------------------------------------------
    -- 10. EXECUTION TIME & SLA CHECK  (SLA = 300 seconds / 5 minutes)
    -- ----------------------------------------------------------------
    v_end_time          := CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ;
    v_execution_seconds := DATEDIFF('second', v_start_time, v_end_time);
    v_sla_met_flag      := CASE WHEN v_execution_seconds <= 300 THEN 'Y' ELSE 'N' END;

    -- ----------------------------------------------------------------
    -- 11. WRITE RECONCILIATION LOG — SUCCESS
    -- ----------------------------------------------------------------
    -- SECTION 5: Reconciliation
INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
        RUN_ID,
        RUN_TIMESTAMP,
        LOAD_TYPE,
        WATERMARK_USED,
        SOURCE_COUNT,
        INSERT_COUNT,
        UPDATE_COUNT,
        DEDUP_COUNT,
        SOFT_DELETE_COUNT,
        TARGET_COUNT_POST_LOAD,
        EXECUTION_SECONDS,
        SLA_MET_FLAG,
        LAST_SUCCESSFUL_RUN_TIMESTAMP,
        STATUS,
        ERROR_MESSAGE
    ) VALUES (
        v_run_id,
        v_run_timestamp,
        v_load_type,
        v_watermark_used,
        v_source_count,
        v_insert_count,
        v_update_count,
        v_dedup_count,
        v_soft_delete_count,
        v_target_count_post,
        v_execution_seconds,
        v_sla_met_flag,
        v_end_time,
        v_status,
        v_error_message
    );

    RETURN OBJECT_CONSTRUCT(
        'status',            v_status,
        'run_id',            v_run_id,
        'load_type',         v_load_type,
        'watermark_used',    v_watermark_used::VARCHAR,
        'source_count',      v_source_count,
        'insert_count',      v_insert_count,
        'update_count',      v_update_count,
        'dedup_count',       v_dedup_count,
        'soft_delete_count', v_soft_delete_count,
        'target_count_post', v_target_count_post,
        'execution_seconds', v_execution_seconds,
        'sla_met_flag',      v_sla_met_flag
    )::VARCHAR;

-- SECTION 6: Error Handling
EXCEPTION
    WHEN OTHER THEN

        v_end_time          := CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ;
        v_execution_seconds := DATEDIFF('second', v_start_time, v_end